### ISSUE TITLE
Telemetry Arduino and CLI

### ISSUE THREAD

**Issue by AIREL46** [Overdrivr/Telemetry-arduino#8]
Here is the detail of my work:
 Loading the Telemetry library into the directory: /Root/Arduino/libraries/Telemetry
Editing the test.ino program (see the attached file)
Upload to the Teensy 3.2 microcontroller
Correct firmware execution by the Teensy 3.2 microcontroller
Cloning of pytelemetry command line interface
Python Version 2.7.12
The question: **how to use the CLI?**

**Comment by AIREL46** [comment]
Here is the detail of my work:
Loading the Telemetry library into the directory: /Root/Arduino/libraries/Telemetry
Editing the test.ino program (see the attached file)
Upload to the Teensy 3.2 microcontroller
Correct firmware execution by the Teensy 3.2 microcontroller
Cloning of pytelemetry command line interface
Python Version 2.7.12
The question: how to use the CLI?
test.ino
#include <Telemetry.h>
int32_t i;
const int led_pin_v = 13;//Led verte

void setup() {
  Serial.begin(9600); // Do not forget to initialize serial
  i = 0;
  delay(1000);
  pinMode(led_pin_v, OUTPUT);
}

void loop() {
  // Send counter value under topic `foo`
  Telemetry.pub_i32("foo", i);
  digitalWrite(led_pin_v, HIGH);
  delay(1000);
  digitalWrite(led_pin_v, LOW);
  delay(1000);
  i++;
}

**Comment by Overdrivr** [comment]
The [README](https://github.com/Overdrivr/pytelemetrycli) is pretty self-explanatory regarding installing and using the command line to read values from the device.

If you have a more **specific** issue (such as a bug), feel free to open another ticket. Please do not open tickets for general-purpose questions such as this one. Be specific.
